In [3]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import gridenv

In [4]:
env = gym.make('noise-v2')

In [5]:
state = env.reset()

In [8]:
s,r,d,i = env.step(0)

check1  0
right outside if


In [9]:
n = 20  
identity = np.identity(n, dtype = np.float32)
original_states = []
flipped_states = []
for i in range(n):
    original_states.append(identity[i])
    flipped_states.append(identity[-(i+1)])

    

In [12]:
print(original_states[0])
print(flipped_states[0])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [30]:
a=[1,3,8]
import random
index = np.arange(0,20,1)
print(index)
random.(index,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


TypeError: Population must be a sequence or set.  For dicts, use list(d).

In [17]:
[x * x for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [38]:
idx = np.random.randint(20, size=5)

In [43]:
original_states=np.array(original_states)

In [44]:
original_states[idx,:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [47]:
noise=np.random.normal(0,1,20)

In [49]:
original_states[idx,:]+noise

array([[-0.82844356, -0.01989501,  1.19833444,  1.09239375,  0.52798479,
         0.84243843, -1.2274856 , -0.42365419,  0.51199724, -1.93478626,
         0.79464491, -0.21895033,  1.56242847,  0.43686255, -0.57460849,
        -0.04930102, -0.13591336,  0.45790691,  0.75823353,  1.33335489],
       [-0.82844356, -0.01989501,  1.19833444,  1.09239375,  0.52798479,
         0.84243843, -1.2274856 ,  0.57634581,  0.51199724, -1.93478626,
         0.79464491, -0.21895033,  1.56242847,  0.43686255, -0.57460849,
        -0.04930102, -0.13591336,  0.45790691,  0.75823353,  0.33335489],
       [-0.82844356, -0.01989501,  1.19833444,  1.09239375,  0.52798479,
         1.84243843, -1.2274856 , -0.42365419,  0.51199724, -1.93478626,
         0.79464491, -0.21895033,  1.56242847,  0.43686255, -0.57460849,
        -0.04930102, -0.13591336,  0.45790691,  0.75823353,  0.33335489],
       [-0.82844356, -0.01989501,  1.19833444,  1.09239375,  1.52798479,
         0.84243843, -1.2274856 , -0.42365419,  